name: Push to Pantheon
description: A GitHub Action that deploys code to Pantheon Dev and Multidev environments
branding:
  icon: activity
  color: yellow
inputs:
  ssh_key:
    description: 'A private key that corresponds to a public key on Pantheon: https://docs.pantheon.io/ssh-keys'
    required: true

  machine_token:
    description: "A token for authenticating with Pantheon's command line: https://docs.pantheon.io/machine-tokens"
    required: true

  site:
    description: 'The machine name of your Pantheon site.'
    required: true

  target_env:
    description: 'The Pantheon environment to which the deployment will be made. If left blank, the value used will be automatically derived. Pull requests will deploy to environments named "pr-[NUMBER]" and main/master branch commits will deploy to the Pantheon "dev" environment'
    required: false
    default: ""

  source_env:
    description: "The environment from which the database and uploaded files will be copied."
    required: false
    default: "live"

  clone_content:
    description: "If set to true, the database and files directory will be re-cloned from the source environment. When set to false, this data is only copied upon Multidev creations. Setting this variable to true ensures fresh content but adds time to the build process that can be prohibitive for sites with large databases."
    required: false
    default: false
    type: boolean

  delete_old_environments:
    description: "If set to true, Multidev environments associated with closed pull requests will be deleted after deployment completes. It is recommended to set this parameter to true for workflows that run after merges to the main branch."
    required: false
    default: false
    type: boolean

  git_user_name:
    description: "The name to be used with the Git commit that will be pushed to Pantheon. This value is not used on newer 'eVCS' sites for which there is no Pantheon-provided Git repo."
    required: false
    default: "Pantheon Automation"

  git_user_email:
    description: "The email address to be used with the Git commit that will be pushed to Pantheon. This value is not used on newer 'eVCS' sites for which there is no Pantheon-provided Git repo."
    required: false
    default: "bot@getpantheon.com"

  git_commit_message:
    description: "A custom commit message to be used with the Git commit that will be pushed to Pantheon. Leaving this Action parameter blank will result in a generic commit message being used. This value is not used on newer 'eVCS' sites for which there is no Pantheon-provided Git repo."
    required: false
    default: ""

  relative_site_root:
    description: "The root directory of the site to be deployed relative to the repository root. The vast majority of users of this action should leave this value unchanged from the default. The action will use this value to change directories after checking out the repo."
    required: false
    default: ""

  skip_terminus_install:
    description: "If set to true, the action will skip the installation of Terminus. This is useful if you are using a custom Docker image that already has Terminus installed or you are installing it earlier in the workflow. By default, the action will check for the presence of Terminus and install it if it is not found, but if this is set to true, the action will bypass the check and skip the Terminus install."
    required: false
    default: false
    type: boolean

  # todo checkout_repo:
  #   description: "A boolean for whether or not this composite step should checkout the git repo. Set to false if a checkout has already been perf"

runs:
    using: 'composite'
    steps:

      - name: Set target_env
        id: set_target_env
        shell: bash
        env:
          PR_NUM: ${{ github.event.pull_request.number }}
          INPUT_TARGET_ENV: ${{ inputs.target_env }}
        run: |
          # Set target_env
          set +e

            if [ -n "${INPUT_TARGET_ENV}" ]; then
              TARGET_ENV="${INPUT_TARGET_ENV}"
            elif [ -n "${PR_NUM}" ]; then
              TARGET_ENV="pr-${PR_NUM}"
            elif [ "${GITHUB_REF}" == "refs/heads/main" ] || [ "${GITHUB_REF}" == "refs/heads/master" ]; then
              TARGET_ENV='dev'
            else
              echo "Error: you must set the 'target_env' parameter when running this action on a branch that is not 'main' or 'master' or when not executing a workflow in a pull request."
              exit 1
            fi

          echo "PANTHEON_TARGET_ENV set to ${TARGET_ENV}"
          echo "PANTHEON_TARGET_ENV=${TARGET_ENV}" >> $GITHUB_ENV

      - name: Set clone content flag
        shell: bash
        env:
          CLONE_CONTENT: ${{ inputs.clone_content }}
        run: |
          # Set clone content flag
          set +e
          if [ "$CLONE_CONTENT" == "true" ]; then
            export CLONE_CONTENT_FLAG="--clone-content"
            echo "Content will be cloned again if the target environment already exists"
          else
            export CLONE_CONTENT_FLAG=""
            echo "Content will NOT be cloned again if the target environment already exists"
          fi

          echo "PANTHEON_CLONE_CONTENT_FLAG=${CLONE_CONTENT_FLAG}" >> $GITHUB_ENV

      - name: Start deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ github.token }}
          env: ${{ env.PANTHEON_TARGET_ENV }}
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Configure SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
            ssh-private-key: ${{ inputs.ssh_key }}

      - name: Check for Terminus
        if: ${{ inputs.skip_terminus_install != 'true' }}
        id: check_terminus
        shell: bash
        run: |
          if command -v terminus &> /dev/null; then
            echo "Terminus detected. Skipping Terminus installation."
            echo "should_install_terminus=false" >> $GITHUB_OUTPUT
          else
            echo "Terminus not installed, proceeding to install."
            echo "should_install_terminus=true" >> $GITHUB_OUTPUT
          fi

      - name: Install Terminus
        if: ${{ inputs.skip_terminus_install != 'true' && steps.check_terminus.outputs.should_install_terminus == 'true' }}
        uses: pantheon-systems/terminus-github-actions@v1
        with:
          pantheon-machine-token: ${{ inputs.machine_token }}

      - name: Install Terminus Plugin
        shell: bash
        run: terminus self:plugin:install "pantheon-systems/terminus-build-tools-plugin:3.x-dev"

      - name: Configure Git User
        shell: bash
        env:
          PANTHEON_GIT_USER_NAME: ${{ inputs.git_user_name }}
          PANTHEON_GIT_USER_EMAIL: ${{ inputs.git_user_email }}
        run: |
          # Configure Git User
          set +e
          git config --global user.email "${PANTHEON_GIT_USER_EMAIL}"
          git config --global user.name "${PANTHEON_GIT_USER_NAME}"

      - name: Prepare site root
        shell: bash
        env:
          SITE_ROOT: ${{ inputs.relative_site_root }}
        run: |
          # Prepare site root
          set +e
          if [ -n "$SITE_ROOT" ]; then
            cd ${SITE_ROOT}
            git init -b main
            git add .
            git commit -m "Initial commit for deployment"
            echo "this origin setting is a hack to get past the 'inferring' of a git provider in build tools"
            git remote add origin https://github.com/${{ github.repository }}
          else
            git fetch --unshallow origin
          fi

      - name: Deployment Processing
        shell: bash
        id: deploy_to_pantheon
        env:
          PANTHEON_SITE: ${{ inputs.site }}
          PANTHEON_SOURCE_ENV: ${{ inputs.source_env }}
          SITE_ROOT: ${{ inputs.relative_site_root }}
          PANTHEON_COMMIT_MESSAGE: ${{ inputs.git_commit_message }}
          GITHUB_TOKEN: ${{ github.token }}
          # todo, might need to make this configurable too.
          # the default in build tools is 180. But that's regularly failing
          # on a small personal site.
          TERMINUS_BUILD_TOOLS_WORKFLOW_TIMEOUT: 300
        run: |
          # Push to Pantheon
          set +e

          if [ -n "$SITE_ROOT" ]; then
            cd ${SITE_ROOT}
          fi

          terminus -n build:env:create ${PANTHEON_SITE}.${PANTHEON_SOURCE_ENV} ${PANTHEON_TARGET_ENV} --yes --message="${PANTHEON_COMMIT_MESSAGE}" ${PANTHEON_CLONE_CONTENT_FLAG}

      - name: Update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ github.token }}
          status: ${{ job.status }}
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          # todo, how does this work when there is a step above with the id of "deployment" not "deployment_id"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env: ${{ env.PANTHEON_TARGET_ENV }}
          env_url: https://${{ env.PANTHEON_TARGET_ENV }}-${{ inputs.site }}.pantheonsite.io
      - name: Deleting old multidevs
        if: ${{ inputs.delete_old_environments == 'true' && steps.deploy_to_pantheon.outcome == 'success' }}
        shell: bash
        env:
          DELETE_OLD_MULTIDEVS: ${{ inputs.delete_old_environments }}
          PANTHEON_SITE: ${{ inputs.site }}
          GITHUB_TOKEN: ${{ github.token }}
          SITE_ROOT: ${{ inputs.relative_site_root }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          MULTIDEV_DELETE_PATTERN: pr-
          PANTHEON_TARGET_ENV: ${{ env.PANTHEON_TARGET_ENV }}
          WORKSPACE: ${{ github.workspace }}
        run: $WORKSPACE/scripts/cleanup.sh
