name: Deploy to Pantheon

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  push-to-pantheon:
    permissions:
      deployments: write
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # The custom theme for this site uses Tailwind to build the
    # appropriate CSS file.
    #- run: "cd web/themes/my_custom_theme && npm ci && npm run build"
    # Deleting this small .gitignore that ignores compiled CSS
    # from the GitHub repo will allow it to be committed and pushed
    # to Pantheon in the later "push-to-pantheon" step.
    #- run: "cd web/themes/my_custom_theme/css && rm .gitignore"
    - name: Push to Pantheon
      uses: pantheon-systems/push-to-pantheon@0.7.0
      with:
        ssh_key: ${{ secrets.PANTHEON_SSH_KEY }}
        machine_token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
        site: ${{ vars.PANTHEON_SITE }}
        source_env: dev